### ISSUE TITLE
Debugging tests with scripts is hard

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/scripts#10]
In case I want to debug a test to understand why it is failing, the fact that the jest config is internalised makes the debug difficult.

Previously all I had to do was

`node --inspect-brk jest --runInBand`. Now that the config is internalised I am forced to do `node --inspect-brk /Users/vncz/dev/stoplight/graph/node_modules/.bin/jest --color=always --config=/Users/vncz/dev/stoplight/graph/node_modules/@stoplight/scripts/jest.config.js oas3 --runInBand`

I'd propose, instead of making the scripts call the configuration file directly so we're forced to call it explicitly every single time — to specify such file in the local package.json file.

**Comment by marbemac** [comment]
Good idea, will get to it shortly!

**Comment by XVincentX** [comment]
This should not be an issue anymore.
