### ISSUE TITLE
Can't resolve '@stoplight/ui-kit/storybook-addon/withThemes'

### ISSUE THREAD

**Issue by wmhilton** [stoplightio/scripts#12]
`Module not found: Error: Can't resolve '@stoplight/ui-kit/storybook-addon/withThemes' in '/Users/wmhilton/code/stoplight/formtron/node_modules/@stoplight/scripts/.storybook'`

Eh?

**Comment by marbemac** [comment]
You need to add `@stoplight/ui-kit` to the repo in question. If you used the `create:lib` command it should have been added by default - was it not?

**Comment by marbemac** [comment]
Ok if you already had that in your deps, then it was this bug: https://github.com/stoplightio/ui-kit/commit/1c2c0acff46db3c4e14ea29eaf910988fa048645

**Comment by marbemac** [comment]
Ultimately, the storybook addon should prob be in a standalone repo so that we don't need to depend on ui-kit just to use storybook theme addon.

**Comment by wmhilton** [comment]
Upgrading to @stoplight/ui-kit@1.6.1 fixed it.
