### ISSUE TITLE
Running sl-scripts for tests is removing the colours from the output

### ISSUE THREAD

**Issue by XVincentX** [stoplightio/scripts#4]
When using jest to test:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/1416224/48338295-9161ef00-e665-11e8-8183-6de0b7b5c549.png">

When using sl-scripts:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/1416224/48338312-9b83ed80-e665-11e8-8fca-ff1041617de2.png">

Colours are really helpful to understand where's the problem at glance. It'd be great to fix this.

**Comment by marbemac** [comment]
Hmm this one is weird - I get colors on my end (this example is in `json-ref-resolver` which uses sl-scripts). Which command are you running?

<img width="743" alt="screen shot 2018-11-12 at 10 54 28 am" src="https://user-images.githubusercontent.com/847542/48362492-61b4e600-e669-11e8-9590-21a763f5531a.png">

**Comment by XVincentX** [comment]
Yeah, they work on the coverage as well as other parts. They do not work on the diffs coming from a failing test. Can you try to make fail a test on purpose and see its output?

**Comment by marbemac** [comment]
Hmm, interesting - I see it. Leave this one to me, will take too much time I think for you to familiarize yourself and debug it. It comes down to https://github.com/shelljs/shelljs - I'll re-work the test command to call jest directly instead of using shelljs to call jest.

Good catch!

**Comment by XVincentX** [comment]
Yes, I noticed that it was due to the underlying library.

Just out of curiosity I was having a look on how `react-scripts` is doing this and they're actually spawning commands using `execSync` directly. https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/test.js#L36
